/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hubberspot.sender;

import Modelo.Alumno;
import SqlLite.controller.Login_Controller;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.annotation.Resource;
import javax.jms.ConnectionFactory;
import javax.jms.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author OSCAR
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private Connection conn;
private ResultSet rst;
private PreparedStatement pst;
 @Resource(mappedName = "jms/myConnectionFactory")
    public static ConnectionFactory connectionFactory;
    
    @Resource(mappedName = "jms/MyQueue")
    public static Queue queue;
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public static Alumno alumno = new Alumno("Oscar", "Yanfer", "19200260", "admin");
    public static String nombre = "";
    public static String apellido = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txUname = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        txUname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblContraseña.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");

        txPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPassActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar sesion.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Proceso Único de Matrícula");

        jLabel3.setText("<html><h1>Iniciar sesión</h1></html>");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txPass, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContraseña)
                            .addComponent(txUname, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txUname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /*
        if(txUname.getText().equalsIgnoreCase(alumno.getCodigo()) && txPass.getText().equalsIgnoreCase(alumno.getContrasena())){
            System.out.println("bienvenido");
            JOptionPane.showMessageDialog(this, "Se encuentra en horario de matricula");
            nombre = alumno.getNombre();
            apellido = alumno.getApellido();
            FrmSender ventana = new FrmSender();
            ventana.setVisible(true);
            this.setVisible(false);

        }
        else{
            System.out.println("error");
        }
        */
        
        String uname,pwd;
        boolean status=false;
   
        uname=txUname.getText();
        pwd=txPass.getText();
        
        Alumno loginModel= new Alumno();
        loginModel.setNombre(uname);
        loginModel.setContrasena(pwd);

        
      Login_Controller model= new Login_Controller(conn);
         status= model.login(loginModel);
         
         if(status==true){

            System.out.println("bienvenido");
            JOptionPane.showMessageDialog(this, "Se encuentra en horario de matricula");
            nombre = alumno.getNombre();
            apellido = alumno.getApellido();
            FrmSender ventana = new FrmSender();
            ventana.setVisible(true);
            this.setVisible(false);
             
         }
         else if(txUname.getText().isEmpty() && String.valueOf(txPass.getPassword()).isEmpty()){
                               JOptionPane.showMessageDialog(rootPane, "Username and Password still empty", "Info", JOptionPane.INFORMATION_MESSAGE);

             
         }
         else if(txUname.getText().equals(""))
         {
                  JOptionPane.showMessageDialog(rootPane, "Username still empty", "Info", JOptionPane.INFORMATION_MESSAGE);
         }else if(String.valueOf(txPass.getPassword()).equals(""))
         {
                  JOptionPane.showMessageDialog(rootPane, "Password still empty", "Info", JOptionPane.INFORMATION_MESSAGE);
                  
         }
 
         else{
               JOptionPane.showMessageDialog(rootPane, "Invalid Username and Password", "Info", JOptionPane.INFORMATION_MESSAGE);
             
         } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void txPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JPasswordField txPass;
    public javax.swing.JTextField txUname;
    // End of variables declaration//GEN-END:variables
}
