/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hubberspot.sender;

import Modelo.Alumno;
import Modelo.Curso;
import Modelo.DatosCurso;
import Modelo.Matricula;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import javax.jms.ConnectionFactory;
import javax.jms.JMSContext;
import javax.jms.JMSProducer;
import javax.jms.Queue;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author luigg
 */
public class FrmSender extends javax.swing.JFrame {
/*
    @Resource(mappedName = "jms/myConnectionFactory")
    private static ConnectionFactory connectionFactory;
    
    @Resource(mappedName = "jms/MyQueue")
    private static Queue queue;
    
  */
    
    /**
     * Creates new form FrmSender
     */
    public FrmSender() {
       
        initComponents();
        
        FrmLogin ventana = new FrmLogin();
        jLabel7.setText(ventana.alumno.getNombre());
        jLabel8.setText(ventana.alumno.getApellido());
        Curso c = new Curso();
        
        c.agregarCursoI("Algoritmica", "Seccion 1", "Wilker Atalaya", "Lunes", "18:00", "22:00");
        c.agregarCursoI("Algoritmica", "Seccion 2", "Jorge Quispe", "Lunes", "18:00", "22:00");
        jLabel1.setText(c.getCursoI(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox1.addItem(c.getCursoI(i).getDocente()+" / "+c.getCursoI(i).getSeccion()
            +" / "+c.getCursoI(i).getDia()+" / Horario: "+c.getCursoI(i).getHoraInicio()+"-"+c.getCursoI(i).getHoraFin());
        }
        
        c.agregarCursoII("Matemática Discreta", "Seccion 1", "Luiggi Pasache", "Martes", "8:00", "12:00");
        c.agregarCursoII("Matemática Discreta", "Seccion 2", "Martin Vizcarra", "Martes", "18:00", "22:00");
        jLabel2.setText(c.getCursoII(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox2.addItem(c.getCursoII(i).getDocente()+" / "+c.getCursoII(i).getSeccion()
            +" / "+c.getCursoII(i).getDia()+" / Horario: "+c.getCursoII(i).getHoraInicio()+"-"+c.getCursoII(i).getHoraFin());
        }
        
        c.agregarCursoIII("Física Electronica", "Seccion 1", "Francisco Sagasti", "Miercoles", "18:00", "22:00");
        c.agregarCursoIII("Física Electronica", "Seccion 2", "Diego Montalvo", "Miercoles", "14:00", "18:00");
        jLabel3.setText(c.getCursoIII(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox3.addItem(c.getCursoIII(i).getDocente()+" / "+c.getCursoIII(i).getSeccion()
            +" / "+c.getCursoIII(i).getDia()+" / Horario: "+c.getCursoIII(i).getHoraInicio()+"-"+c.getCursoIII(i).getHoraFin());
        }
        
        c.agregarCursoIV("Ingeniería Economica", "Seccion 1", "Abimael Guzmán", "Jueves", "17:00", "22:00");
        c.agregarCursoIV("Ingeniería Economica", "Seccion 2", "Pedro Castillo", "Jueves", "8:00", "13:00");
        jLabel4.setText(c.getCursoIV(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox4.addItem(c.getCursoIV(i).getDocente()+" / "+c.getCursoIV(i).getSeccion()
            +" / "+c.getCursoIV(i).getDia()+" / Horario: "+c.getCursoIV(i).getHoraInicio()+"-"+c.getCursoIV(i).getHoraFin());
        }
        
        c.agregarCursoV("Sistemas Digitales", "Seccion 1", "Keiko Fujimori", "Viernes", "8:00", "12:00");
        c.agregarCursoV("Sistemas Digitales", "Seccion 2", "Alan Garcia", "Viernes", "18:00", "22:00");
        jLabel5.setText(c.getCursoV(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox5.addItem(c.getCursoV(i).getDocente()+" / "+c.getCursoV(i).getSeccion()
            +" / "+c.getCursoV(i).getDia()+" / Horario: "+c.getCursoV(i).getHoraInicio()+"-"+c.getCursoV(i).getHoraFin());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emisor");

        jButton1.setText("Matricularse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setToolTipText("");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel6.setText("<html>\n<h1>Matricula</h1>\n</html>");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmLogin ventana = new FrmLogin();
        JMSContext jmsContext = ventana.connectionFactory.createContext();
        JMSProducer jmsProducer = jmsContext.createProducer();
        
        String cursoI = jComboBox1.getSelectedItem().toString();
        String cursoII = jComboBox2.getSelectedItem().toString();
        String cursoIII = jComboBox3.getSelectedItem().toString();
        String cursoIV = jComboBox4.getSelectedItem().toString();
        String cursoV = jComboBox5.getSelectedItem().toString();
        
        
        
        /*Scanner sc = new Scanner(System.in);
        String nombre = sc.nextLine();
        String apellido = sc.nextLine();
        int edad = sc.nextInt();*/
         /*    
        Matricula matricula=new Matricula();
        Alumno alumno=new Alumno();
        Curso curso=new Curso();
        DatosCurso datoscurso=new DatosCurso();
        List<Curso> cursos=new ArrayList<>();
        curso.setDatos(datoscurso);
        cursos.add(curso);
        matricula.setAlumno(alumno);
        matricula.setCursos(cursos);*/
        String messageI = cursoI.toString();
        String messageII = cursoII.toString();
        String messageIII = cursoIII.toString();
        String messageIV = cursoIV.toString();
        String messageV = cursoV.toString();
        
        List<String> matricula = new ArrayList();
        matricula.add(messageI);
        matricula.add(messageII);
        matricula.add(messageIII);
        matricula.add(messageIV);
        matricula.add(messageV);
        matricula.add(ventana.alumno.getNombre());
        matricula.add(ventana.alumno.getApellido());
        
        String str = "";
        for (String matriculas : matricula) {
	str+= matriculas+",";
	}
        
        Alumno al = new Alumno(ventana.alumno.getNombre(), ventana.alumno.getApellido(), ventana.alumno.getCodigo(), ventana.alumno.getContrasena());
        Matricula m = new Matricula(al, str);

        System.out.println("Sending message to JMS - ");
        jmsProducer.send(ventana.queue, str);
        System.out.println("Message send successfully!!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
