
package com.hubberspot.sender;

import Modelo.Alumno;
import Modelo.Curso;
import Modelo.Matricula;
import java.util.ArrayList;
import java.util.List;
import javax.jms.JMSContext;
import javax.jms.JMSProducer;
import javax.swing.JOptionPane;

/**
 *
 * @author luigg
 */
public class FrmSender extends javax.swing.JFrame {
    int a=30, b=30,r=30, d=30,e=30,f=30,h=30,g=30,l=30,j=30; 
/*
    
    @Resource(mappedName = "jms/myConnectionFactory")
    private static ConnectionFactory connectionFactory;
    
    @Resource(mappedName = "jms/MyQueue")
    private static Queue queue;
    
  */
    
    /**
     * Creates new form FrmSender
     */
    public FrmSender() {
       
        initComponents();
         
        this.setLocationRelativeTo(null);
        
        FrmLogin ventana = new FrmLogin();
        jLabel7.setText(ventana.alumno.getNombre());
        jLabel8.setText(ventana.alumno.getApellido());
        Curso c = new Curso();
        
        c.agregarCursoI("Algorítmica", "Seccion 1", "Wilker Atalaya", "Lunes", "22:00", "18:00");
        c.agregarCursoI("Algorítmica", "Seccion 2", "Jorge Quispe", "Lunes", "22:00", "18:00");
        jLabel1.setText(c.getCursoI(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox1.addItem(c.getCursoI(i).getDocente()+" / "+c.getCursoI(i).getSeccion()
            +" / "+c.getCursoI(i).getDia()+" / Horario: "+c.getCursoI(i).getHoraInicio()+"-"+c.getCursoI(i).getHoraFin());
        }
        
        c.agregarCursoII("Matemática Discreta", "Seccion 1", "Luiggi Pasache", "Martes", "12:00", "8:00");
        c.agregarCursoII("Matemática Discreta", "Seccion 2", "Martin Vizcarra", "Martes", "22:00", "18:00");
        jLabel2.setText(c.getCursoII(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox2.addItem(c.getCursoII(i).getDocente()+" / "+c.getCursoII(i).getSeccion()
            +" / "+c.getCursoII(i).getDia()+" / Horario: "+c.getCursoII(i).getHoraInicio()+"-"+c.getCursoII(i).getHoraFin());
        }
        
        c.agregarCursoIII("Física Electrónica", "Seccion 1", "Francisco Sagasti", "Miercoles", "22:00", "18:00");
        c.agregarCursoIII("Física Electrónica", "Seccion 2", "Diego Montalvo", "Miercoles", "18:00", "14:00");
        jLabel3.setText(c.getCursoIII(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox3.addItem(c.getCursoIII(i).getDocente()+" / "+c.getCursoIII(i).getSeccion()
            +" / "+c.getCursoIII(i).getDia()+" / Horario: "+c.getCursoIII(i).getHoraInicio()+"-"+c.getCursoIII(i).getHoraFin());
        }
        
        c.agregarCursoIV("Ingeniería Económica", "Seccion 1", "Carlos Vazquez", "Jueves", "22:00", "17:00");
        c.agregarCursoIV("Ingeniería Económica", "Seccion 2", "Pedro Castillo", "Jueves", "13:00", "8:00");
        jLabel4.setText(c.getCursoIV(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox4.addItem(c.getCursoIV(i).getDocente()+" / "+c.getCursoIV(i).getSeccion()
            +" / "+c.getCursoIV(i).getDia()+" / Horario: "+c.getCursoIV(i).getHoraInicio()+"-"+c.getCursoIV(i).getHoraFin());
        }
        
        c.agregarCursoV("Sistemas Digitales", "Seccion 1", "Keiko Fujimori", "Viernes", "12:00", "8:00");
        c.agregarCursoV("Sistemas Digitales", "Seccion 2", "Alan Garcia", "Viernes", "22:00", "18:00");
        jLabel5.setText(c.getCursoV(0).getCurso());
        for(int i = 0; i < 2; i++){
            jComboBox5.addItem(c.getCursoV(i).getDocente()+" / "+c.getCursoV(i).getSeccion()
            +" / "+c.getCursoV(i).getDia()+" / Horario: "+c.getCursoV(i).getHoraInicio()+"-"+c.getCursoV(i).getHoraFin());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emisor");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 600));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Matricularse");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Curso_1");
        jLabel1.setToolTipText("");

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Curso_2");

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Curso_3");

        jComboBox4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Curso_4");

        jComboBox5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Curso_5");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("<html>\n<h1>Matricula</h1>\n</html>");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Apellido");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Bienvenido:");

        jLabel10.setText("<html><b>Alumno:</b></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmLogin ventana = new FrmLogin();
        JMSContext jmsContext = ventana.connectionFactory.createContext();
        JMSProducer jmsProducer = jmsContext.createProducer();
        
        String cursoI = jComboBox1.getSelectedItem().toString();
        String cursoII = jComboBox2.getSelectedItem().toString();
        String cursoIII = jComboBox3.getSelectedItem().toString();
        String cursoIV = jComboBox4.getSelectedItem().toString();
        String cursoV = jComboBox5.getSelectedItem().toString();
        
        String messageI = new String();
        String messageII= new String();
        String messageIII= new String();
         String messageIV= new String();
         String messageV= new String();
         List<String> matricula = new ArrayList();
         
        if(cursoI=="Wilker Atalaya / Seccion 1 / Lunes / Horario: 18:00-22:00"){
            if(a>0){
              messageI = cursoI.toString();
              
             a--;
             matricula.add(messageI+"/ Vacantes:"+a);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        
       }else{
        if(b>0){
              messageI = cursoI.toString();
             b--;
              matricula.add(messageI+"/ Vacantes:"+b);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
         if(cursoII=="Luiggi Pasache / Seccion 1 / Martes / Horario: 12:00-8:00"){
            if(r>0){
              messageII = cursoII.toString();
              
             r--;
              matricula.add(messageII+"/ Vacantes:"+r);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        
       }else{
        if(d>0){
              messageII = cursoII.toString();
             d--;
              matricula.add(messageII+" / Vacantes:"+d);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        }
         
         
         
         
         if(cursoIII=="Francisco Sagasti / Seccion 1 / Miercoles / Horario: 18:00-22:00"){
            if(e>0){
              messageIII = cursoIII.toString();
             e--;
              matricula.add(messageIII+" / Vacantes:"+e);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        
       }else{
        if(f>0){
              messageIII = cursoIII.toString();
             f--;
              matricula.add(messageIII+"/ Vacantes:"+f);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        }
         
         
         
         
            if(cursoIV=="Carlos Vazquez / Seccion 1 / Jueves / Horario: 17:00-22:00"){
            if(h>0){
              messageIV = cursoIV.toString();
              h--;
               matricula.add(messageIV+" / Vacantes:"+h);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        
       }else{
        if(g>0){
              messageIV = cursoIV.toString();
             g--;
             matricula.add(messageIV+"/ Vacantes:"+g);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        }
       
         
            
           if(cursoV=="Keiko Fujimori / Seccion 1 / Viernes / Horario: 8:00-12:00"){
            if(l>0){
              messageV = cursoV.toString();
             l--;
             matricula.add(messageV+"/ Vacantes:"+l);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        
       }else{
        if(j>0){
              messageV = cursoV.toString();
             j--;
             matricula.add(messageV+"/ Vacantes:"+j);
            }else{
             JOptionPane.showMessageDialog(null, "No hay vacantes! ","error",JOptionPane.ERROR_MESSAGE);
            }
        }
       
     
        
        
        
        matricula.add(ventana.alumno.getNombre());
        matricula.add(ventana.alumno.getApellido());
       
        String str = "";
        for (String matriculas : matricula) {
            System.out.println(matriculas);
	str+= matriculas+",";
	}
        
        Alumno al = new Alumno(ventana.alumno.getNombre(), ventana.alumno.getApellido(), ventana.alumno.getCodigo(), ventana.alumno.getContrasena());
        Matricula m = new Matricula(al, str);

        System.out.println("Sending message to JMS - ");
        jmsProducer.send(ventana.queue, str);
        System.out.println("Message send successfully!!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
